// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Car_HUD_Slave

#include "ui.h"

// COMPONENT MABIAO

lv_obj_t * ui_MABIAO_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_MABIAO;
    cui_MABIAO = lv_label_create(comp_parent);
    lv_obj_set_width(cui_MABIAO, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_MABIAO, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_MABIAO, 1);
    lv_obj_set_y(cui_MABIAO, 4);
    lv_obj_set_align(cui_MABIAO, LV_ALIGN_CENTER);
    lv_label_set_text(cui_MABIAO, "32");

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_MABIAO_NUM);
    children[UI_COMP_MABIAO_MABIAO] = cui_MABIAO;
    lv_obj_add_event_cb(cui_MABIAO, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_MABIAO, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_MABIAO_create_hook(cui_MABIAO);
    return cui_MABIAO;
}

