// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Car_HUD_Slave

#ifndef _CAR_HUD_SLAVE_UI_H
#define _CAR_HUD_SLAVE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_788129694);    // assets/右转向灯.png
LV_IMG_DECLARE(ui_img_2125033867);    // assets/左转向灯.png
LV_IMG_DECLARE(ui_img_2125878674);    // assets/近光灯.png
LV_IMG_DECLARE(ui_img_934278156);    // assets/手刹灯.png
LV_IMG_DECLARE(ui_img_314426297);    // assets/远光灯.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
