// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Car_HUD_Master_UI

#include "../ui.h"

lv_obj_t * ui_about = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_ImgButton2 = NULL;
lv_obj_t * ui_Image1 = NULL;
// event funtions
void ui_event_ImgButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_main_screen_init);
    }
}

// build funtions

void ui_about_screen_init(void)
{
    ui_about = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_about, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_about);
    lv_img_set_src(ui_Image4, &ui_img_img_0038_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 75
    lv_obj_set_x(ui_Image4, 100);
    lv_obj_set_y(ui_Image4, 1);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_about);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -57);
    lv_obj_set_y(ui_Label6, -23);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "主控:ESP32-S3-N16R8");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Font4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_about);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -119);
    lv_obj_set_y(ui_Label7, 1);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "开发平台:");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Font4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_about);
    lv_img_set_src(ui_Image5, &ui_img_arduino_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image5, -60);
    lv_obj_set_y(ui_Image5, 1);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_about);
    lv_img_set_src(ui_Image6, &ui_img_platformio_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 58
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image6, -11);
    lv_obj_set_y(ui_Image6, 6);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_about);
    lv_img_set_src(ui_Image7, &ui_img_2134214083);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image7, 11);
    lv_obj_set_y(ui_Image7, 2);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_about);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -77);
    lv_obj_set_y(ui_Label8, 26);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "API:高德地图,阿里云");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_Font4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton2 = lv_imgbtn_create(ui_about);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_370264377, NULL);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_370264377, NULL);
    lv_obj_set_height(ui_ImgButton2, 30);
    lv_obj_set_width(ui_ImgButton2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton2, -142);
    lv_obj_set_y(ui_ImgButton2, -105);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);

    ui_Image1 = lv_img_create(ui_about);
    lv_img_set_src(ui_Image1, &ui_img_985675730);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 75
    lv_obj_set_x(ui_Image1, 101);
    lv_obj_set_y(ui_Image1, -78);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);

}

void ui_about_screen_destroy(void)
{
    if(ui_about) lv_obj_del(ui_about);

    // NULL screen variables
    ui_about = NULL;
    ui_Image4 = NULL;
    ui_Label6 = NULL;
    ui_Label7 = NULL;
    ui_Image5 = NULL;
    ui_Image6 = NULL;
    ui_Image7 = NULL;
    ui_Label8 = NULL;
    ui_ImgButton2 = NULL;
    ui_Image1 = NULL;

}
