// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Car_HUD_Master_UI

#ifndef UI_ABOUT_H
#define UI_ABOUT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_about
extern void ui_about_screen_init(void);
extern void ui_about_screen_destroy(void);
extern lv_obj_t * ui_about;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label8;
extern void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

