// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Car_HUD_Master_UI

#include "../ui.h"

lv_obj_t * ui_CONTROL = NULL;
lv_obj_t * ui_ImgButton5 = NULL;
lv_obj_t * ui_start = NULL;
lv_obj_t * ui_left = NULL;
lv_obj_t * ui_stop = NULL;
lv_obj_t * ui_right = NULL;
lv_obj_t * ui_far = NULL;
lv_obj_t * ui_near = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Label15 = NULL;
// event funtions
void ui_event_ImgButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_main_screen_init);
    }
}

void ui_event_start(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        (e);
    }
}

void ui_event_left(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        (e);
    }
}

void ui_event_stop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        (e);
    }
}

void ui_event_right(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        (e);
    }
}

void ui_event_far(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        (e);
    }
}

void ui_event_near(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        (e);
    }
}

// build funtions

void ui_CONTROL_screen_init(void)
{
    ui_CONTROL = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CONTROL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton5 = lv_imgbtn_create(ui_CONTROL);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_370264377, NULL);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_370264377, NULL);
    lv_obj_set_height(ui_ImgButton5, 30);
    lv_obj_set_width(ui_ImgButton5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton5, -142);
    lv_obj_set_y(ui_ImgButton5, -105);
    lv_obj_set_align(ui_ImgButton5, LV_ALIGN_CENTER);

    ui_start = lv_btn_create(ui_CONTROL);
    lv_obj_set_width(ui_start, 100);
    lv_obj_set_height(ui_start, 50);
    lv_obj_set_x(ui_start, -60);
    lv_obj_set_y(ui_start, -80);
    lv_obj_set_align(ui_start, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_start, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_start, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_left = lv_btn_create(ui_CONTROL);
    lv_obj_set_width(ui_left, 100);
    lv_obj_set_height(ui_left, 50);
    lv_obj_set_x(ui_left, -60);
    lv_obj_set_y(ui_left, -7);
    lv_obj_set_align(ui_left, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_left, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_left, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_stop = lv_btn_create(ui_CONTROL);
    lv_obj_set_width(ui_stop, 100);
    lv_obj_set_height(ui_stop, 50);
    lv_obj_set_x(ui_stop, 80);
    lv_obj_set_y(ui_stop, -80);
    lv_obj_set_align(ui_stop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_stop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_stop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_right = lv_btn_create(ui_CONTROL);
    lv_obj_set_width(ui_right, 100);
    lv_obj_set_height(ui_right, 50);
    lv_obj_set_x(ui_right, 80);
    lv_obj_set_y(ui_right, -7);
    lv_obj_set_align(ui_right, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_right, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_right, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_far = lv_btn_create(ui_CONTROL);
    lv_obj_set_width(ui_far, 100);
    lv_obj_set_height(ui_far, 50);
    lv_obj_set_x(ui_far, 80);
    lv_obj_set_y(ui_far, 70);
    lv_obj_set_align(ui_far, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_far, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_far, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_near = lv_btn_create(ui_CONTROL);
    lv_obj_set_width(ui_near, 100);
    lv_obj_set_height(ui_near, 50);
    lv_obj_set_x(ui_near, -60);
    lv_obj_set_y(ui_near, 70);
    lv_obj_set_align(ui_near, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_near, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_near, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_CONTROL);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -60);
    lv_obj_set_y(ui_Label5, -80);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "启动");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Font1JIANT3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_CONTROL);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 80);
    lv_obj_set_y(ui_Label10, -80);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "停止");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_Font1JIANT3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_CONTROL);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -60);
    lv_obj_set_y(ui_Label12, -7);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "左转");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_Font1JIANT3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_CONTROL);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 80);
    lv_obj_set_y(ui_Label13, -7);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "右转");
    lv_obj_set_style_text_font(ui_Label13, &ui_font_Font1JIANT3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_CONTROL);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -60);
    lv_obj_set_y(ui_Label14, 70);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "远光灯");
    lv_obj_set_style_text_font(ui_Label14, &ui_font_Font1JIANT3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_CONTROL);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 80);
    lv_obj_set_y(ui_Label15, 70);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "近光灯");
    lv_obj_set_style_text_font(ui_Label15, &ui_font_Font1JIANT3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton5, ui_event_ImgButton5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_start, ui_event_start, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_left, ui_event_left, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_stop, ui_event_stop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_right, ui_event_right, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_far, ui_event_far, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_near, ui_event_near, LV_EVENT_ALL, NULL);

}

void ui_CONTROL_screen_destroy(void)
{
    if(ui_CONTROL) lv_obj_del(ui_CONTROL);

    // NULL screen variables
    ui_CONTROL = NULL;
    ui_ImgButton5 = NULL;
    ui_start = NULL;
    ui_left = NULL;
    ui_stop = NULL;
    ui_right = NULL;
    ui_far = NULL;
    ui_near = NULL;
    ui_Label5 = NULL;
    ui_Label10 = NULL;
    ui_Label12 = NULL;
    ui_Label13 = NULL;
    ui_Label14 = NULL;
    ui_Label15 = NULL;

}
