// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Car_HUD_Master_UI

#ifndef UI_CONTROL_H
#define UI_CONTROL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CONTROL
extern void ui_CONTROL_screen_init(void);
extern void ui_CONTROL_screen_destroy(void);
extern lv_obj_t * ui_CONTROL;
extern void ui_event_ImgButton5(lv_event_t * e);
extern lv_obj_t * ui_ImgButton5;
extern void ui_event_start(lv_event_t * e);
extern lv_obj_t * ui_start;
extern void ui_event_left(lv_event_t * e);
extern lv_obj_t * ui_left;
extern void ui_event_stop(lv_event_t * e);
extern lv_obj_t * ui_stop;
extern void ui_event_right(lv_event_t * e);
extern lv_obj_t * ui_right;
extern void ui_event_far(lv_event_t * e);
extern lv_obj_t * ui_far;
extern void ui_event_near(lv_event_t * e);
extern lv_obj_t * ui_near;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

