// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Car_HUD_Master_UI

#include "../ui.h"

lv_obj_t * ui_GPS = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_ImgButton7 = NULL;
lv_obj_t * ui_Panel5 = NULL;
// event funtions
void ui_event_ImgButton7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_main_screen_init);
    }
}

// build funtions

void ui_GPS_screen_init(void)
{
    ui_GPS = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_GPS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_GPS);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -120);
    lv_obj_set_y(ui_Label2, 103);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "GPS地图");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Font1JIANT3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton7 = lv_imgbtn_create(ui_GPS);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_370264377, NULL);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_370264377, NULL);
    lv_obj_set_height(ui_ImgButton7, 34);
    lv_obj_set_width(ui_ImgButton7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton7, -140);
    lv_obj_set_y(ui_ImgButton7, -101);
    lv_obj_set_align(ui_ImgButton7, LV_ALIGN_CENTER);

    ui_Panel5 = lv_obj_create(ui_GPS);
    lv_obj_set_width(ui_Panel5, 304);
    lv_obj_set_height(ui_Panel5, 181);
    lv_obj_set_x(ui_Panel5, 1);
    lv_obj_set_y(ui_Panel5, 1);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ImgButton7, ui_event_ImgButton7, LV_EVENT_ALL, NULL);

}

void ui_GPS_screen_destroy(void)
{
    if(ui_GPS) lv_obj_del(ui_GPS);

    // NULL screen variables
    ui_GPS = NULL;
    ui_Label2 = NULL;
    ui_ImgButton7 = NULL;
    ui_Panel5 = NULL;

}
