// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Car_HUD_Master_UI

#include "../ui.h"

lv_obj_t * ui_MUSIC = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_ImgButton6 = NULL;
lv_obj_t * ui_Roller1 = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_ImgButton10 = NULL;
lv_obj_t * ui_ImgButton11 = NULL;
// event funtions
void ui_event_ImgButton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_main_screen_init);
    }
}

void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        (e);
    }
}

void ui_event_ImgButton10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        (e);
    }
}

void ui_event_ImgButton11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        (e);
    }
}

// build funtions

void ui_MUSIC_screen_init(void)
{
    ui_MUSIC = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MUSIC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_MUSIC);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -139);
    lv_obj_set_y(ui_Label11, 73);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "音量");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_Font1JIANT3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton6 = lv_imgbtn_create(ui_MUSIC);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_370264377, NULL);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_370264377, NULL);
    lv_obj_set_height(ui_ImgButton6, 30);
    lv_obj_set_width(ui_ImgButton6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton6, -142);
    lv_obj_set_y(ui_ImgButton6, -105);
    lv_obj_set_align(ui_ImgButton6, LV_ALIGN_CENTER);

    ui_Roller1 = lv_roller_create(ui_MUSIC);
    lv_roller_set_options(ui_Roller1, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Roller1, 270);
    lv_obj_set_height(ui_Roller1, 166);
    lv_obj_set_x(ui_Roller1, 16);
    lv_obj_set_y(ui_Roller1, -15);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_Roller1, &ui_font_Font1JIANT3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Roller1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Roller1, lv_color_hex(0x147EFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Roller1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Roller1, &ui_font_Font1JIANT3, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0x46DAF4), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_MUSIC);
    lv_slider_set_range(ui_Slider1, 0, 21);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 17);
    lv_obj_set_height(ui_Slider1, 114);
    lv_obj_set_x(ui_Slider1, 13);
    lv_obj_set_y(ui_Slider1, -16);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xB4C1F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xF31B3E), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_MUSIC);
    lv_obj_set_width(ui_Panel1, 270);
    lv_obj_set_height(ui_Panel1, 45);
    lv_obj_set_x(ui_Panel1, 15);
    lv_obj_set_y(ui_Panel1, -6);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x5E24FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton10 = lv_imgbtn_create(ui_Panel1);
    lv_imgbtn_set_src(ui_ImgButton10, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2071546890, NULL);
    lv_imgbtn_set_src(ui_ImgButton10, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_2071546890, NULL);
    lv_obj_set_width(ui_ImgButton10, 50);
    lv_obj_set_height(ui_ImgButton10, 50);
    lv_obj_set_x(ui_ImgButton10, -60);
    lv_obj_set_y(ui_ImgButton10, 0);
    lv_obj_set_align(ui_ImgButton10, LV_ALIGN_CENTER);

    ui_ImgButton11 = lv_imgbtn_create(ui_Panel1);
    lv_imgbtn_set_src(ui_ImgButton11, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1812466601, NULL);
    lv_imgbtn_set_src(ui_ImgButton11, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1812466601, NULL);
    lv_obj_set_width(ui_ImgButton11, 50);
    lv_obj_set_height(ui_ImgButton11, 50);
    lv_obj_set_x(ui_ImgButton11, 72);
    lv_obj_set_y(ui_ImgButton11, 18);
    lv_obj_set_align(ui_ImgButton11, LV_ALIGN_BOTTOM_MID);

    lv_obj_add_event_cb(ui_ImgButton6, ui_event_ImgButton6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton10, ui_event_ImgButton10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton11, ui_event_ImgButton11, LV_EVENT_ALL, NULL);

}

void ui_MUSIC_screen_destroy(void)
{
    if(ui_MUSIC) lv_obj_del(ui_MUSIC);

    // NULL screen variables
    ui_MUSIC = NULL;
    ui_Label11 = NULL;
    ui_ImgButton6 = NULL;
    ui_Roller1 = NULL;
    ui_Slider1 = NULL;
    ui_Panel1 = NULL;
    ui_ImgButton10 = NULL;
    ui_ImgButton11 = NULL;

}
