// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Car_HUD_Master_UI

#include "../ui.h"

lv_obj_t * ui_main = NULL;
lv_obj_t * ui_TOWeather = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_time = NULL;
lv_obj_t * ui_day = NULL;
lv_obj_t * ui_ImgButton1 = NULL;
lv_obj_t * ui_ImgButton4 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_ImgButton3 = NULL;
lv_obj_t * ui_ImgButton9 = NULL;
lv_obj_t * ui_Label9 = NULL;
// event funtions
void ui_event_TOWeather(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_weather, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_weather_screen_init);
        _ui_screen_delete(&ui_main_screen_destroy);
    }
}

void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_about, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_about_screen_init);
        _ui_screen_delete(&ui_main_screen_destroy);
    }
}

void ui_event_ImgButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_GPS, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_GPS_screen_init);
        _ui_screen_delete(&ui_main_screen_destroy);
    }
}

void ui_event_ImgButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MUSIC, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_MUSIC_screen_init);
        _ui_screen_delete(&ui_main_screen_destroy);
    }
}

void ui_event_ImgButton9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_CONTROL, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_CONTROL_screen_init);
        _ui_screen_delete(&ui_main_screen_destroy);
    }
}

// build funtions

void ui_main_screen_init(void)
{
    ui_main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TOWeather = lv_imgbtn_create(ui_main);
    lv_imgbtn_set_src(ui_TOWeather, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_478665424, NULL);
    lv_imgbtn_set_src(ui_TOWeather, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_478665424, NULL);
    lv_imgbtn_set_src(ui_TOWeather, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_478665424, NULL);
    lv_imgbtn_set_src(ui_TOWeather, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_478665424, NULL);
    lv_obj_set_width(ui_TOWeather, 80);
    lv_obj_set_height(ui_TOWeather, 80);
    lv_obj_set_x(ui_TOWeather, -40);
    lv_obj_set_y(ui_TOWeather, 12);
    lv_obj_set_align(ui_TOWeather, LV_ALIGN_CENTER);

    ui_Label4 = lv_label_create(ui_main);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -47);
    lv_obj_set_y(ui_Label4, 50);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "天气");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Font1JIANT3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_main);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -114);
    lv_obj_set_y(ui_Label3, 50);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "GPS地图");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Font1JIANT3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_main);
    lv_obj_set_width(ui_Panel4, 278);
    lv_obj_set_height(ui_Panel4, 100);
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, -66);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_time, -6);
    lv_obj_set_y(ui_time, -8);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "00:00:00");
    lv_obj_set_style_text_color(ui_time, lv_color_hex(0x550055), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_day, 169);
    lv_obj_set_height(ui_day, 35);
    lv_obj_set_x(ui_day, -48);
    lv_obj_set_y(ui_day, 41);
    lv_obj_set_align(ui_day, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day, "2024/5/9");
    lv_obj_set_style_text_font(ui_day, &ui_font_Font1JIANT3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton1 = lv_imgbtn_create(ui_main);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2092788291, NULL);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_2092788291, NULL);
    lv_obj_set_height(ui_ImgButton1, 51);
    lv_obj_set_width(ui_ImgButton1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton1, -112);
    lv_obj_set_y(ui_ImgButton1, 91);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);

    ui_ImgButton4 = lv_imgbtn_create(ui_main);
    lv_imgbtn_set_src(ui_ImgButton4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_gps1_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton4, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_gps1_png, NULL);
    lv_obj_set_height(ui_ImgButton4, 51);
    lv_obj_set_width(ui_ImgButton4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton4, -112);
    lv_obj_set_y(ui_ImgButton4, 12);
    lv_obj_set_align(ui_ImgButton4, LV_ALIGN_CENTER);

    ui_Label1 = lv_label_create(ui_main);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 30);
    lv_obj_set_y(ui_Label1, 50);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "音乐");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Font1JIANT3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton3 = lv_imgbtn_create(ui_main);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1456262395, NULL);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1456262395, NULL);
    lv_obj_set_width(ui_ImgButton3, 50);
    lv_obj_set_height(ui_ImgButton3, 50);
    lv_obj_set_x(ui_ImgButton3, 30);
    lv_obj_set_y(ui_ImgButton3, 12);
    lv_obj_set_align(ui_ImgButton3, LV_ALIGN_CENTER);

    ui_ImgButton9 = lv_imgbtn_create(ui_main);
    lv_imgbtn_set_src(ui_ImgButton9, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_498010595, NULL);
    lv_imgbtn_set_src(ui_ImgButton9, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_498010595, NULL);
    lv_obj_set_width(ui_ImgButton9, 50);
    lv_obj_set_height(ui_ImgButton9, 50);
    lv_obj_set_x(ui_ImgButton9, 100);
    lv_obj_set_y(ui_ImgButton9, 12);
    lv_obj_set_align(ui_ImgButton9, LV_ALIGN_CENTER);

    ui_Label9 = lv_label_create(ui_main);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 100);
    lv_obj_set_y(ui_Label9, 50);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "控制");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_Font1JIANT3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TOWeather, ui_event_TOWeather, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton4, ui_event_ImgButton4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton3, ui_event_ImgButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton9, ui_event_ImgButton9, LV_EVENT_ALL, NULL);

}

void ui_main_screen_destroy(void)
{
    if(ui_main) lv_obj_del(ui_main);

    // NULL screen variables
    ui_main = NULL;
    ui_TOWeather = NULL;
    ui_Label4 = NULL;
    ui_Label3 = NULL;
    ui_Panel4 = NULL;
    ui_time = NULL;
    ui_day = NULL;
    ui_ImgButton1 = NULL;
    ui_ImgButton4 = NULL;
    ui_Label1 = NULL;
    ui_ImgButton3 = NULL;
    ui_ImgButton9 = NULL;
    ui_Label9 = NULL;

}
