// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Car_HUD_Master_UI

#include "../ui.h"

lv_obj_t * ui_weather = NULL;
lv_obj_t * ui_TabView3 = NULL;
lv_obj_t * ui_tadyweather = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_location = NULL;
lv_obj_t * ui_Weather = NULL;
lv_obj_t * ui_Temp = NULL;
lv_obj_t * ui_futureweather = NULL;
lv_obj_t * ui_RollerWeather = NULL;
lv_obj_t * ui_ImgButton8 = NULL;
// event funtions
void ui_event_ImgButton8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_main_screen_init);
    }
}

// build funtions

void ui_weather_screen_init(void)
{
    ui_weather = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView3 = lv_tabview_create(ui_weather, LV_DIR_RIGHT, 40);
    lv_obj_set_width(ui_TabView3, 315);
    lv_obj_set_height(ui_TabView3, 235);
    lv_obj_set_x(ui_TabView3, 1);
    lv_obj_set_y(ui_TabView3, -1);
    lv_obj_set_align(ui_TabView3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_TabView3, &ui_font_Font1JIANT3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tadyweather = lv_tabview_add_tab(ui_TabView3, "实况天气");

    ui_Image8 = lv_img_create(ui_tadyweather);
    lv_img_set_src(ui_Image8, &ui_img_362795829);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 75
    lv_obj_set_x(ui_Image8, 89);
    lv_obj_set_y(ui_Image8, -66);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_img_create(ui_tadyweather);
    lv_img_set_src(ui_Image9, &ui_img_1655919733);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image9, 91);
    lv_obj_set_y(ui_Image9, 66);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_tadyweather);
    lv_img_set_src(ui_Image10, &ui_img_889722002);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image10, 87);
    lv_obj_set_y(ui_Image10, 2);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_location = lv_label_create(ui_tadyweather);
    lv_obj_set_width(ui_location, 180);
    lv_obj_set_height(ui_location, 20);
    lv_obj_set_x(ui_location, -35);
    lv_obj_set_y(ui_location, 2);
    lv_obj_set_align(ui_location, LV_ALIGN_CENTER);
    lv_label_set_text(ui_location, "地点:");
    lv_obj_set_style_text_font(ui_location, &ui_font_Font1JIANT3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather = lv_label_create(ui_tadyweather);
    lv_obj_set_width(ui_Weather, 180);
    lv_obj_set_height(ui_Weather, 20);
    lv_obj_set_x(ui_Weather, -35);
    lv_obj_set_y(ui_Weather, -60);
    lv_obj_set_align(ui_Weather, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather, "天气:");
    lv_obj_set_style_text_font(ui_Weather, &ui_font_Font1JIANT3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp = lv_label_create(ui_tadyweather);
    lv_obj_set_width(ui_Temp, 180);
    lv_obj_set_height(ui_Temp, 20);
    lv_obj_set_x(ui_Temp, -35);
    lv_obj_set_y(ui_Temp, 66);
    lv_obj_set_align(ui_Temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temp, "温湿度:                                  ");
    lv_obj_set_style_text_font(ui_Temp, &ui_font_Font1JIANT3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_futureweather = lv_tabview_add_tab(ui_TabView3, "预报天气");

    ui_RollerWeather = lv_roller_create(ui_futureweather);
    lv_roller_set_options(ui_RollerWeather,
                          "今天  天气:晴 温度:-5~8 风力：\n周五  天气:晴 温度:-5~8 风力：\n周日  天气:阴 温度:-5~8 风力：",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerWeather, 271);
    lv_obj_set_height(ui_RollerWeather, 208);
    lv_obj_set_x(ui_RollerWeather, -17);
    lv_obj_set_y(ui_RollerWeather, 13);
    lv_obj_set_align(ui_RollerWeather, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_RollerWeather, &ui_font_Font1JIANT3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton8 = lv_imgbtn_create(ui_weather);
    lv_imgbtn_set_src(ui_ImgButton8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_370264377, NULL);
    lv_imgbtn_set_src(ui_ImgButton8, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_370264377, NULL);
    lv_obj_set_height(ui_ImgButton8, 37);
    lv_obj_set_width(ui_ImgButton8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton8, -141);
    lv_obj_set_y(ui_ImgButton8, -98);
    lv_obj_set_align(ui_ImgButton8, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButton8, ui_event_ImgButton8, LV_EVENT_ALL, NULL);

}

void ui_weather_screen_destroy(void)
{
    if(ui_weather) lv_obj_del(ui_weather);

    // NULL screen variables
    ui_weather = NULL;
    ui_TabView3 = NULL;
    ui_tadyweather = NULL;
    ui_Image8 = NULL;
    ui_Image9 = NULL;
    ui_Image10 = NULL;
    ui_location = NULL;
    ui_Weather = NULL;
    ui_Temp = NULL;
    ui_futureweather = NULL;
    ui_RollerWeather = NULL;
    ui_ImgButton8 = NULL;

}
