// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Car_HUD_Master_UI

#ifndef UI_WEATHER_H
#define UI_WEATHER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_weather
extern void ui_weather_screen_init(void);
extern void ui_weather_screen_destroy(void);
extern lv_obj_t * ui_weather;
extern lv_obj_t * ui_TabView3;
extern lv_obj_t * ui_tadyweather;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_location;
extern lv_obj_t * ui_Weather;
extern lv_obj_t * ui_Temp;
extern lv_obj_t * ui_futureweather;
extern lv_obj_t * ui_RollerWeather;
extern void ui_event_ImgButton8(lv_event_t * e);
extern lv_obj_t * ui_ImgButton8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

