// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Car_HUD_Master_UI

#ifndef _CAR_HUD_MASTER_UI_UI_H
#define _CAR_HUD_MASTER_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_main.h"
#include "screens/ui_GPS.h"
#include "screens/ui_weather.h"
#include "screens/ui_about.h"
#include "screens/ui_MUSIC.h"
#include "screens/ui_CONTROL.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_478665424);    // assets/天气 (3).png
LV_IMG_DECLARE(ui_img_2092788291);    // assets/关于我们.png
LV_IMG_DECLARE(ui_img_gps1_png);    // assets/gps1.png
LV_IMG_DECLARE(ui_img_1456262395);    // assets/音乐1.png
LV_IMG_DECLARE(ui_img_498010595);    // assets/菜单_车辆控制1.png
LV_IMG_DECLARE(ui_img_370264377);    // assets/放回2.png
LV_IMG_DECLARE(ui_img_362795829);    // assets/天气1-1.png
LV_IMG_DECLARE(ui_img_1655919733);    // assets/温湿度.png
LV_IMG_DECLARE(ui_img_889722002);    // assets/地点.png
LV_IMG_DECLARE(ui_img_img_0038_png);    // assets/IMG_0038.png
LV_IMG_DECLARE(ui_img_arduino_png);    // assets/arduino.png
LV_IMG_DECLARE(ui_img_platformio_png);    // assets/platformio.png
LV_IMG_DECLARE(ui_img_2134214083);    // assets/vscode (1).png
LV_IMG_DECLARE(ui_img_985675730);    // assets/湖北科技学院-logo-512px.png
LV_IMG_DECLARE(ui_img_2071546890);    // assets/下一个 下一首1.png
LV_IMG_DECLARE(ui_img_1812466601);    // assets/播放1.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1JIANT);
LV_FONT_DECLARE(ui_font_Font1JIANT2);
LV_FONT_DECLARE(ui_font_Font1JIANT3);
LV_FONT_DECLARE(ui_font_Font4);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
